/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GasReticulationRouteImport } from './routes/gas-reticulation'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SafetySystemsRouteImport } from './routes/safety-systems'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SmartMeteringRouteImport } from './routes/smart-metering'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StorageDesignRouteImport } from './routes/storage-design'
import { Route as TechnicalSpecificationsRouteImport } from './routes/technical-specifications'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleInvestorsRouteImport } from './routes/_authenticated/console.investors'
import { Route as AuthenticatedConsoleJobsRouteImport } from './routes/_authenticated/console.jobs'
import { Route as AuthenticatedConsoleOrdersRouteImport } from './routes/_authenticated/console.orders'
import { Route as AuthenticatedConsolePostsRouteImport } from './routes/_authenticated/console.posts'
import { Route as AuthenticatedConsoleProjectsRouteImport } from './routes/_authenticated/console.projects'
import { Route as AuthenticatedConsoleQuoteBuilderRouteImport } from './routes/_authenticated/console.quote-builder'
import { Route as AuthenticatedConsoleQuotesRouteImport } from './routes/_authenticated/console.quotes'
import { Route as AuthenticatedConsoleShopRouteImport } from './routes/_authenticated/console.shop'
import { Route as AuthenticatedConsoleSubmissionsRouteImport } from './routes/_authenticated/console.submissions'
import { Route as AuthenticatedConsoleUsersRouteImport } from './routes/_authenticated/console.users'
import { Route as ApiPublicEnquiryAttachmentRouteImport } from './routes/api/public/enquiry-attachment'
import { Route as ApiPublicKopokopoWebhookRouteImport } from './routes/api/public/kopokopo-webhook'
import { Route as AuthenticatedConsoleJobsIdRouteImport } from './routes/_authenticated/console.jobs.$id'
import { Route as AuthenticatedConsolePostsIdRouteImport } from './routes/_authenticated/console.posts.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as ApiPublicProjectPdfSlugRouteImport } from './routes/api/public/project-pdf.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GasReticulationRoute = GasReticulationRouteImport.update({
  id: '/gas-reticulation',
  path: '/gas-reticulation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySystemsRoute = SafetySystemsRouteImport.update({
  id: '/safety-systems',
  path: '/safety-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMeteringRoute = SmartMeteringRouteImport.update({
  id: '/smart-metering',
  path: '/smart-metering',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageDesignRoute = StorageDesignRouteImport.update({
  id: '/storage-design',
  path: '/storage-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalSpecificationsRoute = TechnicalSpecificationsRouteImport.update({
  id: '/technical-specifications',
  path: '/technical-specifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleInvestorsRoute =
  AuthenticatedConsoleInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleJobsRoute =
  AuthenticatedConsoleJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleOrdersRoute =
  AuthenticatedConsoleOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePostsRoute =
  AuthenticatedConsolePostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleProjectsRoute =
  AuthenticatedConsoleProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleQuoteBuilderRoute =
  AuthenticatedConsoleQuoteBuilderRouteImport.update({
    id: '/quote-builder',
    path: '/quote-builder',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleQuotesRoute =
  AuthenticatedConsoleQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleShopRoute =
  AuthenticatedConsoleShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSubmissionsRoute =
  AuthenticatedConsoleSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleUsersRoute =
  AuthenticatedConsoleUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const ApiPublicEnquiryAttachmentRoute =
  ApiPublicEnquiryAttachmentRouteImport.update({
    id: '/api/public/enquiry-attachment',
    path: '/api/public/enquiry-attachment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKopokopoWebhookRoute =
  ApiPublicKopokopoWebhookRouteImport.update({
    id: '/api/public/kopokopo-webhook',
    path: '/api/public/kopokopo-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConsoleJobsIdRoute =
  AuthenticatedConsoleJobsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConsoleJobsRoute,
  } as any)
const AuthenticatedConsolePostsIdRoute =
  AuthenticatedConsolePostsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConsolePostsRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectPdfSlugRoute = ApiPublicProjectPdfSlugRouteImport.update({
  id: '/api/public/project-pdf/$slug',
  path: '/api/public/project-pdf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gas-reticulation': typeof GasReticulationRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-systems': typeof SafetySystemsRoute
  '/services': typeof ServicesRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/staff-login': typeof StaffLoginRoute
  '/storage-design': typeof StorageDesignRoute
  '/technical-specifications': typeof TechnicalSpecificationsRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/console/investors': typeof AuthenticatedConsoleInvestorsRoute
  '/console/jobs': typeof AuthenticatedConsoleJobsRouteWithChildren
  '/console/orders': typeof AuthenticatedConsoleOrdersRoute
  '/console/posts': typeof AuthenticatedConsolePostsRouteWithChildren
  '/console/projects': typeof AuthenticatedConsoleProjectsRoute
  '/console/quote-builder': typeof AuthenticatedConsoleQuoteBuilderRoute
  '/console/quotes': typeof AuthenticatedConsoleQuotesRoute
  '/console/shop': typeof AuthenticatedConsoleShopRoute
  '/console/submissions': typeof AuthenticatedConsoleSubmissionsRoute
  '/console/users': typeof AuthenticatedConsoleUsersRoute
  '/api/public/enquiry-attachment': typeof ApiPublicEnquiryAttachmentRoute
  '/api/public/kopokopo-webhook': typeof ApiPublicKopokopoWebhookRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/jobs/$id': typeof AuthenticatedConsoleJobsIdRoute
  '/console/posts/$id': typeof AuthenticatedConsolePostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/project-pdf/$slug': typeof ApiPublicProjectPdfSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gas-reticulation': typeof GasReticulationRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-systems': typeof SafetySystemsRoute
  '/services': typeof ServicesRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/staff-login': typeof StaffLoginRoute
  '/storage-design': typeof StorageDesignRoute
  '/technical-specifications': typeof TechnicalSpecificationsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/console/investors': typeof AuthenticatedConsoleInvestorsRoute
  '/console/jobs': typeof AuthenticatedConsoleJobsRouteWithChildren
  '/console/orders': typeof AuthenticatedConsoleOrdersRoute
  '/console/posts': typeof AuthenticatedConsolePostsRouteWithChildren
  '/console/projects': typeof AuthenticatedConsoleProjectsRoute
  '/console/quote-builder': typeof AuthenticatedConsoleQuoteBuilderRoute
  '/console/quotes': typeof AuthenticatedConsoleQuotesRoute
  '/console/shop': typeof AuthenticatedConsoleShopRoute
  '/console/submissions': typeof AuthenticatedConsoleSubmissionsRoute
  '/console/users': typeof AuthenticatedConsoleUsersRoute
  '/api/public/enquiry-attachment': typeof ApiPublicEnquiryAttachmentRoute
  '/api/public/kopokopo-webhook': typeof ApiPublicKopokopoWebhookRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/jobs/$id': typeof AuthenticatedConsoleJobsIdRoute
  '/console/posts/$id': typeof AuthenticatedConsolePostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/project-pdf/$slug': typeof ApiPublicProjectPdfSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gas-reticulation': typeof GasReticulationRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-systems': typeof SafetySystemsRoute
  '/services': typeof ServicesRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/staff-login': typeof StaffLoginRoute
  '/storage-design': typeof StorageDesignRoute
  '/technical-specifications': typeof TechnicalSpecificationsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/_authenticated/console/investors': typeof AuthenticatedConsoleInvestorsRoute
  '/_authenticated/console/jobs': typeof AuthenticatedConsoleJobsRouteWithChildren
  '/_authenticated/console/orders': typeof AuthenticatedConsoleOrdersRoute
  '/_authenticated/console/posts': typeof AuthenticatedConsolePostsRouteWithChildren
  '/_authenticated/console/projects': typeof AuthenticatedConsoleProjectsRoute
  '/_authenticated/console/quote-builder': typeof AuthenticatedConsoleQuoteBuilderRoute
  '/_authenticated/console/quotes': typeof AuthenticatedConsoleQuotesRoute
  '/_authenticated/console/shop': typeof AuthenticatedConsoleShopRoute
  '/_authenticated/console/submissions': typeof AuthenticatedConsoleSubmissionsRoute
  '/_authenticated/console/users': typeof AuthenticatedConsoleUsersRoute
  '/api/public/enquiry-attachment': typeof ApiPublicEnquiryAttachmentRoute
  '/api/public/kopokopo-webhook': typeof ApiPublicKopokopoWebhookRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/jobs/$id': typeof AuthenticatedConsoleJobsIdRoute
  '/_authenticated/console/posts/$id': typeof AuthenticatedConsolePostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/project-pdf/$slug': typeof ApiPublicProjectPdfSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gas-reticulation'
    | '/industries'
    | '/insights'
    | '/investors'
    | '/marketplace'
    | '/projects'
    | '/quote'
    | '/reset-password'
    | '/safety-systems'
    | '/services'
    | '/smart-metering'
    | '/staff-login'
    | '/storage-design'
    | '/technical-specifications'
    | '/console'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/console/investors'
    | '/console/jobs'
    | '/console/orders'
    | '/console/posts'
    | '/console/projects'
    | '/console/quote-builder'
    | '/console/quotes'
    | '/console/shop'
    | '/console/submissions'
    | '/console/users'
    | '/api/public/enquiry-attachment'
    | '/api/public/kopokopo-webhook'
    | '/console/'
    | '/console/jobs/$id'
    | '/console/posts/$id'
    | '/api/public/media/$'
    | '/api/public/project-pdf/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gas-reticulation'
    | '/industries'
    | '/insights'
    | '/investors'
    | '/marketplace'
    | '/projects'
    | '/quote'
    | '/reset-password'
    | '/safety-systems'
    | '/services'
    | '/smart-metering'
    | '/staff-login'
    | '/storage-design'
    | '/technical-specifications'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/console/investors'
    | '/console/jobs'
    | '/console/orders'
    | '/console/posts'
    | '/console/projects'
    | '/console/quote-builder'
    | '/console/quotes'
    | '/console/shop'
    | '/console/submissions'
    | '/console/users'
    | '/api/public/enquiry-attachment'
    | '/api/public/kopokopo-webhook'
    | '/console'
    | '/console/jobs/$id'
    | '/console/posts/$id'
    | '/api/public/media/$'
    | '/api/public/project-pdf/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/gas-reticulation'
    | '/industries'
    | '/insights'
    | '/investors'
    | '/marketplace'
    | '/projects'
    | '/quote'
    | '/reset-password'
    | '/safety-systems'
    | '/services'
    | '/smart-metering'
    | '/staff-login'
    | '/storage-design'
    | '/technical-specifications'
    | '/_authenticated/console'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/_authenticated/console/investors'
    | '/_authenticated/console/jobs'
    | '/_authenticated/console/orders'
    | '/_authenticated/console/posts'
    | '/_authenticated/console/projects'
    | '/_authenticated/console/quote-builder'
    | '/_authenticated/console/quotes'
    | '/_authenticated/console/shop'
    | '/_authenticated/console/submissions'
    | '/_authenticated/console/users'
    | '/api/public/enquiry-attachment'
    | '/api/public/kopokopo-webhook'
    | '/_authenticated/console/'
    | '/_authenticated/console/jobs/$id'
    | '/_authenticated/console/posts/$id'
    | '/api/public/media/$'
    | '/api/public/project-pdf/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GasReticulationRoute: typeof GasReticulationRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  InvestorsRoute: typeof InvestorsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetySystemsRoute: typeof SafetySystemsRoute
  ServicesRoute: typeof ServicesRoute
  SmartMeteringRoute: typeof SmartMeteringRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StorageDesignRoute: typeof StorageDesignRoute
  TechnicalSpecificationsRoute: typeof TechnicalSpecificationsRoute
  ApiPublicEnquiryAttachmentRoute: typeof ApiPublicEnquiryAttachmentRoute
  ApiPublicKopokopoWebhookRoute: typeof ApiPublicKopokopoWebhookRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicProjectPdfSlugRoute: typeof ApiPublicProjectPdfSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas-reticulation': {
      id: '/gas-reticulation'
      path: '/gas-reticulation'
      fullPath: '/gas-reticulation'
      preLoaderRoute: typeof GasReticulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-systems': {
      id: '/safety-systems'
      path: '/safety-systems'
      fullPath: '/safety-systems'
      preLoaderRoute: typeof SafetySystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-metering': {
      id: '/smart-metering'
      path: '/smart-metering'
      fullPath: '/smart-metering'
      preLoaderRoute: typeof SmartMeteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-design': {
      id: '/storage-design'
      path: '/storage-design'
      fullPath: '/storage-design'
      preLoaderRoute: typeof StorageDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-specifications': {
      id: '/technical-specifications'
      path: '/technical-specifications'
      fullPath: '/technical-specifications'
      preLoaderRoute: typeof TechnicalSpecificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/investors': {
      id: '/_authenticated/console/investors'
      path: '/investors'
      fullPath: '/console/investors'
      preLoaderRoute: typeof AuthenticatedConsoleInvestorsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/jobs': {
      id: '/_authenticated/console/jobs'
      path: '/jobs'
      fullPath: '/console/jobs'
      preLoaderRoute: typeof AuthenticatedConsoleJobsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/orders': {
      id: '/_authenticated/console/orders'
      path: '/orders'
      fullPath: '/console/orders'
      preLoaderRoute: typeof AuthenticatedConsoleOrdersRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/posts': {
      id: '/_authenticated/console/posts'
      path: '/posts'
      fullPath: '/console/posts'
      preLoaderRoute: typeof AuthenticatedConsolePostsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/projects': {
      id: '/_authenticated/console/projects'
      path: '/projects'
      fullPath: '/console/projects'
      preLoaderRoute: typeof AuthenticatedConsoleProjectsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/quote-builder': {
      id: '/_authenticated/console/quote-builder'
      path: '/quote-builder'
      fullPath: '/console/quote-builder'
      preLoaderRoute: typeof AuthenticatedConsoleQuoteBuilderRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/quotes': {
      id: '/_authenticated/console/quotes'
      path: '/quotes'
      fullPath: '/console/quotes'
      preLoaderRoute: typeof AuthenticatedConsoleQuotesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/shop': {
      id: '/_authenticated/console/shop'
      path: '/shop'
      fullPath: '/console/shop'
      preLoaderRoute: typeof AuthenticatedConsoleShopRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/submissions': {
      id: '/_authenticated/console/submissions'
      path: '/submissions'
      fullPath: '/console/submissions'
      preLoaderRoute: typeof AuthenticatedConsoleSubmissionsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/users': {
      id: '/_authenticated/console/users'
      path: '/users'
      fullPath: '/console/users'
      preLoaderRoute: typeof AuthenticatedConsoleUsersRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/api/public/enquiry-attachment': {
      id: '/api/public/enquiry-attachment'
      path: '/api/public/enquiry-attachment'
      fullPath: '/api/public/enquiry-attachment'
      preLoaderRoute: typeof ApiPublicEnquiryAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kopokopo-webhook': {
      id: '/api/public/kopokopo-webhook'
      path: '/api/public/kopokopo-webhook'
      fullPath: '/api/public/kopokopo-webhook'
      preLoaderRoute: typeof ApiPublicKopokopoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/jobs/$id': {
      id: '/_authenticated/console/jobs/$id'
      path: '/$id'
      fullPath: '/console/jobs/$id'
      preLoaderRoute: typeof AuthenticatedConsoleJobsIdRouteImport
      parentRoute: typeof AuthenticatedConsoleJobsRoute
    }
    '/_authenticated/console/posts/$id': {
      id: '/_authenticated/console/posts/$id'
      path: '/$id'
      fullPath: '/console/posts/$id'
      preLoaderRoute: typeof AuthenticatedConsolePostsIdRouteImport
      parentRoute: typeof AuthenticatedConsolePostsRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-pdf/$slug': {
      id: '/api/public/project-pdf/$slug'
      path: '/api/public/project-pdf/$slug'
      fullPath: '/api/public/project-pdf/$slug'
      preLoaderRoute: typeof ApiPublicProjectPdfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConsoleJobsRouteChildren {
  AuthenticatedConsoleJobsIdRoute: typeof AuthenticatedConsoleJobsIdRoute
}

const AuthenticatedConsoleJobsRouteChildren: AuthenticatedConsoleJobsRouteChildren =
  {
    AuthenticatedConsoleJobsIdRoute: AuthenticatedConsoleJobsIdRoute,
  }

const AuthenticatedConsoleJobsRouteWithChildren =
  AuthenticatedConsoleJobsRoute._addFileChildren(
    AuthenticatedConsoleJobsRouteChildren,
  )

interface AuthenticatedConsolePostsRouteChildren {
  AuthenticatedConsolePostsIdRoute: typeof AuthenticatedConsolePostsIdRoute
}

const AuthenticatedConsolePostsRouteChildren: AuthenticatedConsolePostsRouteChildren =
  {
    AuthenticatedConsolePostsIdRoute: AuthenticatedConsolePostsIdRoute,
  }

const AuthenticatedConsolePostsRouteWithChildren =
  AuthenticatedConsolePostsRoute._addFileChildren(
    AuthenticatedConsolePostsRouteChildren,
  )

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleInvestorsRoute: typeof AuthenticatedConsoleInvestorsRoute
  AuthenticatedConsoleJobsRoute: typeof AuthenticatedConsoleJobsRouteWithChildren
  AuthenticatedConsoleOrdersRoute: typeof AuthenticatedConsoleOrdersRoute
  AuthenticatedConsolePostsRoute: typeof AuthenticatedConsolePostsRouteWithChildren
  AuthenticatedConsoleProjectsRoute: typeof AuthenticatedConsoleProjectsRoute
  AuthenticatedConsoleQuoteBuilderRoute: typeof AuthenticatedConsoleQuoteBuilderRoute
  AuthenticatedConsoleQuotesRoute: typeof AuthenticatedConsoleQuotesRoute
  AuthenticatedConsoleShopRoute: typeof AuthenticatedConsoleShopRoute
  AuthenticatedConsoleSubmissionsRoute: typeof AuthenticatedConsoleSubmissionsRoute
  AuthenticatedConsoleUsersRoute: typeof AuthenticatedConsoleUsersRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleInvestorsRoute: AuthenticatedConsoleInvestorsRoute,
  AuthenticatedConsoleJobsRoute: AuthenticatedConsoleJobsRouteWithChildren,
  AuthenticatedConsoleOrdersRoute: AuthenticatedConsoleOrdersRoute,
  AuthenticatedConsolePostsRoute: AuthenticatedConsolePostsRouteWithChildren,
  AuthenticatedConsoleProjectsRoute: AuthenticatedConsoleProjectsRoute,
  AuthenticatedConsoleQuoteBuilderRoute: AuthenticatedConsoleQuoteBuilderRoute,
  AuthenticatedConsoleQuotesRoute: AuthenticatedConsoleQuotesRoute,
  AuthenticatedConsoleShopRoute: AuthenticatedConsoleShopRoute,
  AuthenticatedConsoleSubmissionsRoute: AuthenticatedConsoleSubmissionsRoute,
  AuthenticatedConsoleUsersRoute: AuthenticatedConsoleUsersRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GasReticulationRoute: GasReticulationRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRouteWithChildren,
  InvestorsRoute: InvestorsRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetySystemsRoute: SafetySystemsRoute,
  ServicesRoute: ServicesRoute,
  SmartMeteringRoute: SmartMeteringRoute,
  StaffLoginRoute: StaffLoginRoute,
  StorageDesignRoute: StorageDesignRoute,
  TechnicalSpecificationsRoute: TechnicalSpecificationsRoute,
  ApiPublicEnquiryAttachmentRoute: ApiPublicEnquiryAttachmentRoute,
  ApiPublicKopokopoWebhookRoute: ApiPublicKopokopoWebhookRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicProjectPdfSlugRoute: ApiPublicProjectPdfSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
